services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  api:
    build: .
    restart: unless-stopped
    ports: 
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
