[tool.ruff]
extend-select = [
    "F",    # pyflakes
    "E",    # pycodestyle
    "I",    # isort
    "B",    # flake8-bugbear
    "N",    # pep8-naming
    "S",    # flake8-bandit
    "A",    # flake8-builtins
    "ARG",  # flake8-unused-arguments
    "PLR",  # refactor
    "PIE",  # flake8-pie
    "RET",  # flake8-return
    "RUF",  # ruff-specific rules
]

exclude = []

select = ["E", "F", "I", "N", "S"]

show-fixes = true
ignore = ["RUF003"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
