name: Pre-commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linter

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

        name: Install deps
      - run: pip install -r requirements.dev.txt

        name: Run pre-commit
      - run: pre-commit run --all-files
